import express from 'express';
import handlebars from 'express-handlebars';
import path from 'path'; 
import { Exception, __dirname } from './utils.js';

import indexRouter from './routers/views/index.router.js';
import usersRouter from './routers/api/users.router.js';
import businessRouter from './routers/api/business.router.js';
import ordersRouter from './routers/api/orders.router.js';

const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, '../public')));
app.engine('handlebars', handlebars.engine());
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'handlebars');


app.use('/', indexRouter);
app.use('/api/users', usersRouter);
app.use('/api/business', businessRouter);
app.use('/api/orders', ordersRouter);

app.use((error, req, res, next) => {
    if (error instanceof Exception) {
        res.status(error.status).json({ status: 'error', message: error.message });
    } else {
        const message = `Ah ocurrido un error desconocido: ${error.message}`;
        console.log(message);
        res.status(500).json({ status: 'error', message });
    }
});

export default app;
